#! /bin/bash

echo "____pulling changes"
git pull

function update_implementation {
    impl=$1
    echo "____updating: $impl"
    status=$(./is-submodule-stale $impl)
    if [ "$status" == "different" ]
    then
        echo "____$impl out of date"
        ./roll-submodule $impl
    else
        echo "____$impl OK"
    fi
}

cat implementations | while read impl; do update_implementation $impl; done

echo "____pushing changes"
git push
